### ISSUE TITLE
remove intellij / eclipse project files

### ISSUE THREAD

**Issue by jimkont** [dbpedia/DataId-Ontology#5]
Do we need the IDE files here?

**Comment by seebi** [comment]
in case of eclipse file, its an Xturtle project file which holds metadata to correctly import the ontology. and its directory independent so any xturtle user can reuse it.

**Comment by jimkont** [comment]
ok good, can we remove what is not needed and add a readme file explaining how to use it or links to documentation?

**Comment by chile12** [comment]
removed .idea, added gitignore
