### ISSUE TITLE
Move DMP extension here

### ISSUE THREAD

**Issue by jimkont** [dbpedia/DataId-Ontology#6]
@chile12 should we move the dmp extension in this repo?

**Comment by seebi** [comment]
If you plan to release and version the ontology core and its extensions separately, you should not put it in one repository.

**Comment by jimkont** [comment]
dmp is mostly stable now and we can align the versioning if needed.
Keeping them in separate repositories will add more overhead for publishing

**Comment by chile12** [comment]
DMP is quiet closely connected with the purposes of (core) dataid. This has
manifested itself by properties seeping from dmp to dataid (eg similar
data, software requirement). DMP is not stable yet since there are still
details to figure out (like repository descriptions). See draft version for
more.
@Dimitris: i'm not sure about your question, since DMP has already a branch in this repo

**Comment by chile12** [comment]
Hello everyone,

as you might have noticed we had some troubling issues with abstracts files
in general and English abstracts in particular.

We have remedied those issues by rerunning the full abstract extractions
 for the 10 languages most affected by these issues
(de,en,es,fr,it,ja,ko,nl,pl,pt).

Secondarily, we used this as an opportunity to test the the NLP Interchange
Format (NIF)
http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core/nif-core.htmlextraction
on the abstracts of those languages, extraction three new datasets in the
process:
- _nif-context_: the full text of a page as context (including begin and
  end index)
- _nif-page-structure_: the structure of the page in sections and
  paragraphs (titles, subsections etc.)
- _nif-text-links_: all in-text links to other DBpedia resources as well
  as external references

While for this test run we only include the first section (the abstract) of
every page in the context, we are trying (hopefully by the next release) to
extend the context to the full text of all Wikipedia pages, portraying its
structure and providing the foundation for future NLP fact extraction tasks.

You can download these files from here
http://wiki.dbpedia.org/nif-abstract-datasetsor directly here
http://downloads.dbpedia.org/2016-04/ext/nif-abstracts/.

Furthermore, Magnus discovered that all Wikidata normalized files
(wkd_uris) for the English language edition had faulty predicates, so we
reproduced these as well.

We hope to have covered all shortcomings of the last release by this
measure.

Please note: Patrick from Open Link is still in the process of updating the
public endpoint of DBpedia with the new abstracts while I'm writing this
message.

Markus Freudenberg

Release Manager, DBpedia http://wiki.dbpedia.org
